### ISSUE TITLE
Couldn't locate bindings file

### ISSUE THREAD

**Issue by zarulizham** [dashpay/bitcore-dash#3]
When I execute `bitcored`, the error exists as picture below.

<img width="572" alt="screen shot 2017-12-11 at 2 34 09 pm" src="https://user-images.githubusercontent.com/10229855/33818547-8b4cc100-de80-11e7-8e01-7fe704413dba.png">

Is there any step I did missed?

**Comment by antouhou** [comment]
Hello @zarulizham! Which system are you using? Do you have zeromq installed on your machine?

**Comment by Alex-Werner** [comment]
Closing this as we never had an answer to the above question which probably fixed with the solution proposed and described in the documentation (requirement ZMQ).
Feel free to reopen it if not.
