### ISSUE TITLE
Deprecated packages in NPM

### ISSUE THREAD

**Issue by figassis** [dashpay/bitcore-dash#5]
I'm trying to build a docker container and I keep getting deprecated warnings when running
`npm install -g bitcore-dash`

```
npm WARN deprecated bitcore-lib-dash@0.13.21: Deprecated - Please use https://www.npmjs.com/package/@dashevo/dashcore-lib
npm WARN deprecated insight-api-dash@0.4.5: Deprecated - please use https://www.npmjs.com/package/@dashevo/insight-api
```

And then the whole install fails with:
```
> bitcore-node-dash@3.0.6 preinstall /usr/local/lib/node_modules/bitcore-dash/node_modules/bitcore-node-dash
> ./scripts/download

Downloading dash: https://bamboo.dash.org/browse/DASHL-REL-13/artifact/JOB1/gitian-linux-dash-dist/dashcore-0.12.2-linux64.tar.gz
 npm WARN deprecated bitcore-lib-dash@0.15.3: Deprecated - Please use https://www.npmjs.com/package/@dashevo/dashcore-lib
npm ERR! Linux 4.9.87-linuxkit-aufs
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bitcore-dash"
npm ERR! node v4.9.1
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! bitcore-node-dash@3.0.6 preinstall: `./scripts/download`
npm ERR! Exit status 22
npm ERR! 
npm ERR! Failed at the bitcore-node-dash@3.0.6 preinstall script './scripts/download'.
npm ERR! This is most likely a problem with the bitcore-node-dash package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/download
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bitcore-node-dash
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls bitcore-node-dash
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

**Comment by nmarley** [comment]
Hi, the `bitcore-node-dash` package is deprecated and not supported. Please use `@dashevo/dashcore-node` instead.

**Comment by figassis** [comment]
I had also tried that and npm kept pulling the old one instead.

Here's what I did instead:
Dockerfile: https://github.com/figassis/docker-bitcore/blob/dash/Dockerfile
Config: https://github.com/figassis/bitcore/blob/master/dashmainnet/bitcore-node-dash.json
Docker:

Testnet
```docker run -d --restart=always --name dashtest -p 3001:3001 -p 19998:9998 -p 19999:19999 -v ./dashtestnet:/root/.dashcore figassis/docker-bitcore:dash```

Mainnet
```docker run -d --restart=always --name dashmain -p 3002:3001 -p 9998:9998 -p 9999:9999 -v ./dashmainnet:/root/.dashcore figassis/docker-bitcore:dash```

**Comment by nmarley** [comment]
I guess that works too! I personally wouldn't recommend putting it all into one container, as it makes it difficult for Docker itself to manage the daemons running inside (dashcore and the Node.js service).

For your Docker commands I would recommend using a `docker-compose.json` file if it makes it easier.

Note also that we're dropping support for Node < 6 in most projects, so you might want to update soon.

Thanks for contributing!
